### ISSUE TITLE
Cannot install from Gradle

### ISSUE THREAD

**Issue by eddydn** [gturedi/StatefulLayout#1]
Dear Gturedi

Your StatefulLayout can't be install from Gradle

Please check

**Comment by gturedi** [comment]
hi could you share your project and app level build.gradle files?

**Comment by eddydn** [comment]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2',
{
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'
    testCompile 'junit:junit:4.12'

    compile 'com.github.gturedi:StatefulLayout:1.1.1'
}


Here you are (set on build.gradle module.app)


2017-02-28 14:10 GMT+07:00 Gökhan Türedi <notifications@github.com>:

**Comment by gturedi** [comment]
my fault i typed wrong artifactId. i fixed it, thanks! 

compile 'com.github.gturedi:StatefulLayout:1.1.0' > compile 'com.github.gturedi:stateful-layout:1.1.0' 

https://oss.sonatype.org/#nexus-search;quick~com.github.gturedi

**Comment by eddydn** [comment]
Thank you ;) Really cool layout

2017-02-28 14:41 GMT+07:00 Gökhan Türedi <notifications@github.com>:
