### ISSUE TITLE
Would like to change default icon color

### ISSUE THREAD

**Issue by santhoshrao519** [gturedi/StatefulLayout#10]
I would like to replace the color of the icon, at current it is showing pink color, is there any possibility to do that?

**Comment by gturedi** [comment]
you can can it defining @color/stfImageColor resource

**Comment by santhoshrao519** [comment]
please elaborate your answer with an example. I get stuck at this point

**Comment by gturedi** [comment]
you should put line like below in app/res/values/color.xml file:
 <color name="stfImageColor">#000000</color>

**Comment by santhoshrao519** [comment]
like this <color name="stfImageColor">#000000</color>  ??
