### ISSUE TITLE
showContent() methode doesn't work 

### ISSUE THREAD

**Issue by samirthebti** [gturedi/StatefulLayout#2]
I tried to show the content of recyclerView after loading data from internet , but the show method look like she have an unexpectedly behaviour  ?

**Comment by gturedi** [comment]
hi, could you share your layout and activity code?

**Comment by mibac138** [comment]
Hello!

I have the same problem. After investigation I think the problem occurs when the delay between showing loading screen and showing content is smaller than the animation's length.
In other words it occurs if `stContainer` changes before the animation can complete.
Example:
```java
statefulLayout.showLoading();
// Animation plays (900ms by default)
// Time *less* than 900ms passes (ex. 300ms)
statefulLayout.showContent();
// Loading is showed -- expected content to be showed
```

**Comment by zunjae** [comment]
This issue is still in the library!

Here is what happens

1) You connect to a server
2) you see nothing on your screen
3) for a brief moment you see the results on screen, WITHOUT CALLING .showcontent()
4) the loading indicator appears.

I'm using 1.2.1
