### ISSUE TITLE
Button custom text

### ISSUE THREAD

**Issue by aykuttasil** [gturedi/StatefulLayout#4]
Merhaba
showError() gibi action larda çıkan button text ini özelleştiremiyoruz. **Retry** yerine **Tekrar Dene** demek istiyorum örneğin. 
Ellerinize sağlık.

**Comment by gturedi** [comment]
selam @aykuttasil

xml'de override edebilirsin:
`<string name="stfButtonText">Tekrar Dene</string>`

ya da kod tarafında showCustom() metodunu kullabilirsin:
`     showCustom(new CustomStateOptions()
                .message(message)
                .image(R.drawable.stf_ic_error)
                .buttonText("Tekrar Dene") // burası!
                .buttonClickListener(clickListener));`

**Comment by aykuttasil** [comment]
Süper :)
Teşekkürler.
