### ISSUE TITLE
The library is not working!

### ISSUE THREAD

**Issue by Shajeel-Afzal** [gturedi/StatefulLayout#6]
Hi, 

I have followed the steps that you have mentioned in the ReadMe and also the sample to use this library in my app but none of the methods like `showError`, `showProgress` etc is working for me.

Please help!

**Comment by gturedi** [comment]
hi did you get exception? if true can you share it

**Comment by Shajeel-Afzal** [comment]
@gturedi I am not able to call any of the library methods.

**Comment by gturedi** [comment]
if you correctly import library you should use StatefulLayout class, can you get reference of it?

**Comment by Rainer-Lang** [comment]
@Shajeel-Afzal Any update on this? Please give further information - or close this issue, if all is solved now. Thanks.
